name: Deploy Sashakt webapp to production

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout tagged version
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            rm -rf sashakt-webapp

            git clone https://github.com/sashakt-platform/sashakt-webapp.git
            cd sashakt-webapp

            echo "Checking out version tag..."
            git checkout ${{ github.ref_name }}

            echo "BACKEND_URL=${{ vars.BACKEND_URL }}" > .env
            echo "TEST_TAKER_URL=${{ vars.TEST_TAKER_URL }}" >> .env

            corepack enable
            sudo corepack prepare pnpm@latest --activate

            echo "Installing dependencies..."
            pnpm install

            echo "Building the project..."
            pnpm run build

            echo "Restarting or starting the application with pm2..."
            if [ -f "build/index.js" ]; then
              pm2 restart sashakt-webapp --update-env || pm2 start build/index.js --name sashakt-webapp
            else
              echo "Build output not found: build/index.js"
              exit 1
            fi
