name: Deploy to Production

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (example: v1.2.3)'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            rm -rf sashakt-webapp

            # Determine tag to deploy: prefer manual input, then event tag
            DISPATCH_TAG="${{ github.event.inputs.tag }}"
            GITHUB_REF="${{ github.ref }}"
            TARGET_TAG="$DISPATCH_TAG"

            if [ -z "$TARGET_TAG" ]; then
              if [[ "$GITHUB_REF" == refs/tags/* ]]; then
                TARGET_TAG="${GITHUB_REF#refs/tags/}"
              fi
            fi

            if [ -z "$TARGET_TAG" ]; then
              echo "No tag supplied via workflow_dispatch and this event is not a tag push. Aborting."
              exit 1
            fi

            echo "Cloning tag: $TARGET_TAG"
            git clone --branch "$TARGET_TAG" --depth 1 https://github.com/sashakt-platform/sashakt-webapp.git sashakt-webapp || \
            (git clone https://github.com/sashakt-platform/sashakt-webapp.git sashakt-webapp && cd sashakt-webapp && git fetch --all --tags && git checkout -f "$TARGET_TAG")

            cd sashakt-webapp

            echo "BACKEND_URL=${{ vars.BACKEND_URL }}" > .env

            corepack enable
            sudo corepack prepare pnpm@latest --activate

            pnpm install
            pnpm run build

            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            if [ -f "build/index.js" ]; then
              pm2 restart sashakt-webapp --update-env || pm2 start build/index.js --name sashakt-webapp
            else
              echo "Build output not found: build/index.js"
              exit 1
            fi
